

spring:
    profiles:
        active:  dev
    mvc:
      pathmatch:
            matching-strategy: ANT_PATH_MATCHER

---

spring:
    profiles: dev
server:
    port: 8080

---

spring:
    profiles: sit
    
server:
    port: 9080

---

spring:
    profiles: uat
    
server:
    port: 9090