

spring:
    profiles:
        active:  dev
    mvc:
      pathmatch:
            matching-strategy: ANT_PATH_MATCHER

---

spring:
  config:
    activate:
      on-profile: dev
server:
    port: 8080

---

spring:
  config:
    activate:
      on-profile: sit
server:
    port: 9080

---

spring:
  config:
    activate:
      on-profile: uat
server:
    port: 9090