

spring:
    profiles:
        active:  dev

---

spring:
    profiles: dev
    mvc:
      pathmatch:
            matching-strategy: ANT_PATH_MATCHER
server:
    port: 8080

---

spring:
    profiles: sit
    mvc:
      pathmatch:
            matching-strategy: ANT_PATH_MATCHER
server:
    port: 9080

---

spring:
    profiles: uat
    mvc:
      pathmatch:
            matching-strategy: ANT_PATH_MATCHER
server:
    port: 9090